version: "2"

services:
 mysql-wp:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=wp
   - MYSQL_DATABASE=wp
   - MYSQL_USER=wp
   - MYSQL_PASSWORD=wp
  volumes:
   - ./data/mysql-wp:/var/lib/mysql
  restart: always
   
 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  links:
    - mysql-wp:db
  depends_on:
   - mysql-wp
  ports:
    - 8083:80
  environment:
   - PMA_PORT=3306
   - MYSQL_USER=wp
   - MYSQL_PASSWORD=wp
   - MYSQL_ROOT_PASSWORD=wp
   
 wordpress:
  image: wordpress
  ports:
   - 80:80
  links:
   - mysql-wp:db
  depends_on:
   - mysql-wp
  volumes:
   - ./persist/wp-content:/var/www/html/wp-content 
  environment:
   - WORDPRESS_DB_HOST=db:3306
   - WORDPRESS_DB_PASSWORD=wp
  restart: always
   
 